import type { Metadata } from 'next'
import '@styles/globals.scss'
import Navbar from '@/components/Navbar'
import { IBM_Plex_Mono  } from 'next/font/google'
import Footer from '@/components/Footer'

// const inter = Inter({ subsets: ['latin'] })

const ibm = IBM_Plex_Mono({
  subsets: ['latin'],
  variable: '--font-ibm',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
